{% set name = "jaraco.context" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jaraco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2aa8ca1ac7301b9034c17fc7b0b444faea194c4ded2d6909fa9d8fe723aefee4

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=56
    - setuptools_scm >=3.4.1
  run:
    - python >=3.6

test:
  imports:
    - jaraco.context

about:
  home: https://github.com/jaraco/jaraco.context
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Context managers by jaraco
  doc_url: https://jaracocontext.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.context

extra:
  recipe-maintainers:
    - carlodri
