{% set name = "jaraco.context" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jaraco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 874699efb4275caa7838efe605c11b88ecd8d55e894fcba8eafd3fd04d3dc387

build:
  skip: True  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=77
    - toml
  run:
    - python
    - backports.tarfile  # [py<312]

test:
  imports:
    - jaraco.context
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jaraco/jaraco.context
  license: MIT
  license_family: MIT
  summary: Context managers by jaraco
  # no description provided
  doc_url: https://jaracocontext.readthedocs.io
  dev_url: https://github.com/jaraco/jaraco.context

extra:
  recipe-maintainers:
    - carlodri
